### PR TITLE
Added a padding feature.

### PR DESCRIPTION
**Pull request by gp-97**
### Padding feature
Can be used for applying padding to a PhotonImage in four different ways:
| `photon_rs::transform::padding_uniform` : Applies an uniform padding around the PhotonImage.|
|----|
|t6_padded_uniform|

| `photon_rs::transform::padding_top` : Applies padding on the top side of a PhotonImage | `photon_rs::transform::padding_right` : Applies padding on the right side of a PhotonImage |
|------|------|
|t6_padded_top|t6_padded_right|

|  `photon_rs::transform::padding_left` : Applies padding on the left side of a PhotonImage. | `photon_rs::transform::padding_bottom` : Applies padding on the bottom side of a PhotonImage|
|---------|--------|
|t6_padded_left|t6_padded_bottom|

### CODE REVIEW

**Comment by Daggy1234** [comment]
Looks great,but just 2 questions

1) Why a seperate file for the method, why not add it under transformations

2) Maybe a way to change the color of the padding

Anyway apart from that looks great!. Just run rustfmt for the CI

**Comment by gp-97** [comment]
> Looks great,but just 2 questions
> 
>     1. Why a seperate file for the method, why not add it under transformations
> 
>     2. Maybe a way to change the color of the padding
> 
> 
> Anyway apart from that looks great!. Just run rustfmt for the CI

1. Yeah, I will move it into transformations.rs
2. I will add a color option for padding.

**Review by silvia-odwyer — APPROVED** [review]
Looks great to me! 😄

**Comment by silvia-odwyer** [comment]
@gp-97 Thanks so much for your great contribution! It'll be useful to have padding functionality! Going to merge this now ✅

**Comment by silvia-odwyer** [comment]
Also, thanks @Daggy1234 for requesting those changes, I agreed with those! Much appreciated 👍

**Pull request merged**
