### PR TITLE
Added a new effect: "Frosted Glass"

### PR DESCRIPTION
**Pull request by gp-97**
# Frosted Glass

I have created a crate for generating [Perlin noise in 2D](https://crates.io/crates/perlin2d), using which I have created the `frosted glass` effect.

## Example Usage:
```rust
use photon_rs::native::{open_image, save_image};
use photon_rs::PhotonImage;
use photon_rs::effects::frosted_glass;

let mut img = open_image("image.jpg").expect("File not found");
frosted_glass(&mut img);

save_image(img, "image_frosted.jpg");
```
## Example Outputs:
| OriginaI image| Frosted Glass Image|
|------------------|----------------------------|
|image0|image0_result|
|image2|image2_result|
|image1|image1_result|
|image3|image3_result|

### CODE REVIEW

**Comment by Daggy1234** [comment]
Okay Some notes here

1) All library image effects take in a `&mut PhotonImage` and manipulate the image in place. So modify for consistency
2) Update docstrings and return for the same.

**Comment by gp-97** [comment]
> Okay Some notes here
> 
>     1. All library image effects take in a `&mut PhotonImage` and manipulate the image in place. So modify for consistency
> 
>     2. Update docstrings and return for the same.

I have made the necessary changes. Thanks for pointing them out.

**Comment by silvia-odwyer** [comment]
@gp-97 Wow, thanks so much for the great contribution! I really love this effect, it's super cool I must say 😄

**Review by silvia-odwyer — APPROVED** [review]
The code looks great to me, and yes I agreed with @Daggy1234's notes about changing the parameter so that it accepts a mutable PhotonImage, as well as the documentation. Those items seem to be fixed; I'll merge this now ✅ Thanks again!

**Pull request merged**
