### PR TITLE
Add CI with github & actions-rs

### PR DESCRIPTION
**Pull request by elpiel**
It seems there is no CI integration and although there is no actual feature request I though I would add it and open a discussion for it.

The `Cargo.toml` for workspace is there because the actions run from the main directory for the repository and can't run within a sub-folder (as far as I looked into it)

Another consideration would be to commit the `Cargo.lock` file with the exact locked version of dependencies

### TODOs:

- [x] Run `rustfmt` - to fix all formatting
- [x] Fix `clippy` errors - primarily unused imports from what I see
- [ ] ~add Cargo.lock?!~

### CODE REVIEW

**Comment by elpiel** [comment]
@silvia-odwyer could you enable the checks for the PRs and branches?
I think this is why they don't show or run right now or it could be because I have no permissions to the repository, not really sure.

Screenshot_2020-10-22 AeroRust arsdk-rs

**Comment by elpiel** [comment]
I did manage to break the `wasm-pack build` because I've removed some imports that `clippy` was complaining so I've added also a `check` for `wasm32-unknown-unknown` target.

Also here's proof that this now works:
https://github.com/elpiel/photon/pull/1

**Note:** I had to clean up the benchmark file as well as there were unused imports and functions. Are they going to be used or they are obsolete?

**Review by silvia-odwyer — APPROVED** [review]
Looks great to me! The unused imports in the benchmarks file are obsolete yes, they were left there after testing the benchmarks, so we can keep those removed. I'll also enable status checks in this repository once this is merged ✅

**Comment by silvia-odwyer** [comment]
@elpiel I just added the hacktoberfest-accepted label also, thanks again! 🎉

**Comment by elpiel** [comment]
No worries and thanks as well!
PS: It's time to put those sweet sweet build badge icons now :D Maybe a `good first issue` for newcomers :P

**Comment by silvia-odwyer** [comment]
@elpiel That's a great idea about the build badges, I'll make sure to create that issue! 😄

**Pull request merged**
