### PR TITLE
support random noise by import js_sys::Math::random function

### PR DESCRIPTION
**Pull request by benliao**

### CODE REVIEW

**Comment by silvia-odwyer** [comment]
@benliao Thanks very much for your contribution, it's greatly appreciated! 😄 It's great to have WASM support for the noise filters. I'm just wondering if you could run `cargo fmt` on the directory so that the formatting test will pass. I will then merge your contribution ✅

**Comment by benliao** [comment]
@silvia-odwyer, sorry for missing run "cargo fmt" the new commit has run cargo fmt and no modification to cargo.toml, with contributor information in the readme. thanks.

**Comment by benliao** [comment]
@silvia-odwyer The noise function has been added to the webpack demo, the cargo test passed, and the cargo formatted. The add_noise_rand function parameter and return changed to work with the webpack demo and aligned with other interfaces.

**Comment by benliao** [comment]
@silvia-odwyer, Sorry to bother you; just fixed the Clippy check fail.

**Pull request merged**
